name: Test Renovate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: yu-iskw/test-renovate@v1
        with:
          name: "Renovate"
